// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXKKDV2R6WYjfYqBHX6330UiVBuy854-s',
    appId: '1:1010096059021:web:151dd3ac6121ff4e0a28c4',
    messagingSenderId: '1010096059021',
    projectId: 'elos-rubrik',
    authDomain: 'elos-rubrik.firebaseapp.com',
    storageBucket: 'elos-rubrik.firebasestorage.app',
    measurementId: 'G-94Y2W6L0E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fln_Ht0e2L7S-art2K4AohN2W8wszq4',
    appId: '1:1010096059021:android:d70d2c07075ef6e40a28c4',
    messagingSenderId: '1010096059021',
    projectId: 'elos-rubrik',
    storageBucket: 'elos-rubrik.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXKKDV2R6WYjfYqBHX6330UiVBuy854-s',
    appId: '1:1010096059021:web:1bf971f0a8fd21ca0a28c4',
    messagingSenderId: '1010096059021',
    projectId: 'elos-rubrik',
    authDomain: 'elos-rubrik.firebaseapp.com',
    storageBucket: 'elos-rubrik.firebasestorage.app',
    measurementId: 'G-TXS25JNQ0J',
  );

}